In [2]:
import tensorflow as tf

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/

In [2]:
#定义 2版本下可以直接运行
cons1 = tf.constant(100.0)
cons2 = tf.constant(200.0)
res = tf.add(cons1, cons2)
print(res)

''' 低版本下
#执行1
sess = tf.Session()
print(sess.run(res))
sess.close()

#执行2
with tf.Session as sess:
    print(sess.run(res))
'''

Tensor("Add:0", shape=(), dtype=float32)


In [3]:
'''python3.6下安装1.14版
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl
'''

'python3.6下安装1.14版\npip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl\n'

In [2]:
#定义
cons1 = tf.constant(100.0)
cons2 = tf.constant(200.0)
res = tf.add(cons1, cons2)

with tf.Session() as sess:
    print(sess.run(res))  #张量可以直接eval()

300.0


In [3]:
#图

In [5]:
#定义
const1 = tf.constant(100.0)
const2 = tf.constant(200.0)
res = tf.add(const1, const2)

#获取默认的图
graph = tf.get_default_graph()
print('默认的图：', graph)

#运行
with tf.Session() as sess:
    print(sess.run(res))
    print(const1.graph)
    print(const2.graph)
    print(res.graph)

默认的图： <tensorflow.python.framework.ops.Graph object at 0x7fc4fdebedd8>
300.0


In [7]:
#多图，创建多个图，指定session运行

In [4]:
#定义
const1 = tf.constant(100.0)
const2 = tf.constant(200.0)
res = tf.add(const1, const2)

#获取默认的图
graph = tf.get_default_graph()
print('默认的图：', graph)

#新建一个图
new_graph = tf.Graph()
with new_graph.as_default():
    new_op = tf.constant('hello world')

#运行
with tf.Session(graph=new_graph) as sess:
    #print(sess.run(res))
    print(sess.run(new_op))

#运行
with tf.Session(graph=graph) as sess:
    print(sess.run(res), 'fs')

    sess2 = tf.Session()
    print(sess2.run(res), 'tt')
    sess2.close()

#运行
with tf.Session(graph=graph) as sess:
    print(sess.run(res))

默认的图： <tensorflow.python.framework.ops.Graph object at 0x7fb3d0f4c908>
b'hello world'
300.0 fs
300.0 tt
300.0


In [22]:
#op常用属性

In [6]:
#定义
const1 = tf.constant([1, 2, 3, 4, 5, 6, 7], dtype=tf.int64)
#const2 = tf.constant(2) 这样的张量是一个标量
with tf.Session(graph=graph) as sess:
    print(sess.run(const1))
    print('name', const1.name)
    print('dtype', const1.dtype)
    print('shape', const1.shape)
    print('======='*3)
    print('op', const1.op)
    print('******'*3)
    print('graph', const1.graph)

[1 2 3 4 5 6 7]
name Const_4:0
dtype <dtype: 'int64'>
shape (7,)
op name: "Const_4"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_INT64
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_INT64
      tensor_shape {
        dim {
          size: 7
        }
      }
      tensor_content: "\001\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\005\000\000\000\000\000\000\000\006\000\000\000\000\000\000\000\007\000\000\000\000\000\000\000"
    }
  }
}

******************
graph <tensorflow.python.framework.ops.Graph object at 0x7fb3d0f4c908>


In [30]:
#生成张量

In [3]:
import numpy as np

In [12]:
#定义
const1 = tf.constant(100.0)
const2 = tf.constant([1, 2, 3, 4, 5, 6])
const3 = tf.constant(np.arange(1, 9).reshape(2, 2, 2))
zeros = tf.zeros(shape=[2, 3], dtype='float32')
ones = tf.ones(shape=[2, 3], dtype=tf.float32)
zeros_like = tf.zeros_like(const3)

random = tf.random_normal(shape=[10], mean=0.0, stddev=1, dtype=tf.float32)

#运行
with tf.Session() as sess:
    print(const1.eval())
    print(const2.eval())
    print(const3.eval())
    print(zeros.eval())
    print(ones.eval())
    print(zeros_like.eval())
    print(random.eval())

100.0
[1 2 3 4 5 6]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[ 1.4785254  -0.13488592 -0.5877037  -1.1561906  -0.14415306  0.8864245
  1.1650217  -1.3983389  -0.5287708  -0.42708033]


In [13]:
#张量数据类型的转换

In [16]:
ones = tf.ones(shape=[2, 3], dtype='int64')
tensor1 = tf.constant([1.1, 2.2, 3.3], dtype='float32')
temp = tf.cast(ones, 'float32')
temp_str = tf.cast(tensor1, tf.string)
with tf.Session() as sess:
    print(temp.eval())
    #print(temp_str.eval())  #浮点类型不能转字符串

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#占位符

In [21]:
plhd = tf.placeholder(dtype=tf.float32, shape=[None, 3])  #行数是样本数量，所以不固定，但是列数是神经元个数，那么一定会固定
data = np.arange(1, 7).reshape(2, 3)
with tf.Session() as sess:
    print(sess.run(plhd, feed_dict={plhd: data}))

[[1. 2. 3.]
 [4. 5. 6.]]


In [23]:
#张量的静态形状
#静态形状：初始状态，只能设置一次，固定下来就不能设置了

In [38]:
plhd = tf.placeholder(dtype=tf.float32, shape=[None, 3])
print(plhd)

Tensor("Placeholder_13:0", shape=(?, 3), dtype=float32)


In [40]:
plhd = tf.placeholder(dtype=tf.float32, shape=[None, 3])
plhd.set_shape([4, 3])
print(plhd)

Tensor("Placeholder_15:0", shape=(4, 3), dtype=float32)


In [34]:
plhd.set_shape([3, 4])  #一旦固定就不能再修改了
print(plhd)

ValueError: Dimension 0 in both shapes must be equal, but are 4 and 3. Shapes are [4,3] and [3,4].

In [35]:
#动态形状,同字符串修改一样， 不改变原来的张量，而是修改后，赋值给新张量
a = 'hello world'
b = a.replace(' ', '+')

In [ ]:
#动态形状

In [36]:
new_plhd = tf.reshape(plhd, [1, 4, 3])
print(new_plhd)

Tensor("Reshape_1:0", shape=(1, 4, 3), dtype=float32)


In [41]:
#张量的数学运算

In [43]:
x = tf.constant([[1, 2], [3, 4]], dtype='float32')
y = tf.constant([[4, 3], [2, 1]], dtype='float32')
add = tf.add(x, y)
mul = tf.matmul(x, y)
log = tf.log(x)  #自然对数
reduce_sum = tf.reduce_sum(x, axis=1)  #水平方向求和
#计算片段和
data = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ids = tf.constant([0, 0, 0, 1, 1, 1, 1, 1, 2, 2])
segment = tf.segment_sum(data=data, segment_ids=ids)

with tf.Session() as sess:
    print(add.eval())
    print(mul.eval())
    print(log.eval())
    print(reduce_sum.eval())
    print(segment.eval())

[[5. 5.]
 [5. 5.]]
[[ 8.  5.]
 [20. 13.]]
[[0.        0.6931472]
 [1.0986123 1.3862944]]
[3. 7.]
[ 6 30 19]


In [47]:
#变量,用到变量必须进行初始化，初始化也是op

In [48]:
weight = tf.random_normal(shape=[2, 3])
var = tf.Variable(initial_value=weight)

#初始化
init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)  #当定义一个变量时，需要在会话中进行初始化
    print(sess.run(var))

[[ 1.3942643   0.26474926  0.25010285]
 [-1.3674018   0.65457994  0.79963946]]
